### PR TITLE
Update tcl-version to 8.6.13 from 8.6.12

### PR DESCRIPTION
**Pull request by zosopentoolsmain**

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
I believe 'bump' generated the change to the version.
Should we add a comment on the end of the line so that it's obvious a tool is doing this update and not a human?

**Comment by v1gnesh** [comment]
Bump-generated ones are using the user - zosopentoolsmain and stick to this specific subject format.

https://github.com/ZOSOpenTools/meta/blob/5399f1fadcad7ca97eb73d175eecae98f3471ae2/actions/action.yml#L19

**Comment by HarithaIBM** [comment]
The tclsh binary - is not running as expected and it is causing segmentation fault. Analysing this

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Pull request merged**
